# Copyright (c) 2023 - 2026 Chair for Design Automation, TUM
# Copyright (c) 2025 - 2026 Munich Quantum Software Company GmbH
# All rights reserved.
#
# SPDX-License-Identifier: MIT
#
# Licensed under the MIT License

"""Sphinx configuration file."""

from __future__ import annotations

import sys
from importlib import metadata
from pathlib import Path
from typing import TYPE_CHECKING

import pybtex.plugin
from pybtex.style.formatting.unsrt import Style as UnsrtStyle
from pybtex.style.template import field, href

if TYPE_CHECKING:
    from pybtex.database import Entry
    from pybtex.richtext import HRef

sys.path.insert(0, str(Path(__file__).parent / "_ext"))


try:
    version = metadata.version("mqt.core")
except ModuleNotFoundError:
    msg = "mqt.core must be installed to build the documentation"
    raise ModuleNotFoundError(msg) from None

# Filter git details from version
release = version.split("+")[0]

project = "MQT Core"
author = "Chair for Design Automation, TUM & Munich Quantum Software Company GmbH"
language = "en"
project_copyright = "2023 - 2026 Chair for Design Automation, TUM & 2025 - 2026 Munich Quantum Software Company GmbH"

master_doc = "index"

templates_path = ["_templates"]

extensions = [
    "autoapi.extension",
    "cpp_api",
    "myst_nb",
    "sphinx_copybutton",
    "sphinx_design",
    "sphinx_llm.txt",
    "sphinx.ext.autodoc",
    "sphinx.ext.intersphinx",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinxcontrib.bibtex",
    "sphinxext.opengraph",
]

source_suffix = [".rst", ".md"]

exclude_patterns = [
    "_build",
    "**.ipynb_checkpoints",
    "**.jupyter_cache",
    "**jupyter_execute",
    "Thumbs.db",
    ".DS_Store",
    ".env",
    ".venv",
    # These files are generated by mlir-tblgen and are included by the parent
    # MLIR pages. They are not standalone Sphinx documents.
    "mlir/Conversions/*.md",
    "mlir/Dialects/*.md",
    "mlir/Passes/*.md",
]

pygments_style = "colorful"

intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "numpy": ("https://numpy.org/doc/stable/", None),
    "qiskit": ("https://quantum.cloud.ibm.com/docs/api/qiskit", None),
    "pennylane": ("https://docs.pennylane.ai/en/stable/", None),
    "mqt": ("https://mqt.readthedocs.io/en/latest", None),
    "ddsim": ("https://mqt.readthedocs.io/projects/ddsim/en/latest", None),
    "qmap": ("https://mqt.readthedocs.io/projects/qmap/en/latest", None),
    "qcec": ("https://mqt.readthedocs.io/projects/qcec/en/latest", None),
    "qecc": ("https://mqt.readthedocs.io/projects/qecc/en/latest", None),
    "syrec": ("https://mqt.readthedocs.io/projects/syrec/en/latest", None),
}

myst_enable_extensions = [
    "amsmath",
    "colon_fence",
    "substitution",
    "deflist",
    "dollarmath",
]
myst_substitutions = {
    "version": version,
}
myst_heading_anchors = 3

# -- Options for {MyST}NB ----------------------------------------------------

nb_execution_mode = "cache"
nb_execution_raise_on_error = True


class CDAStyle(UnsrtStyle):
    """Custom style for including PDF links."""

    def format_url(self, _e: Entry) -> HRef:  # ruff:ignore[no-self-use]
        """Format URL field as a link to the PDF.

        Returns:
            The formatted URL field.
        """
        url = field("url", raw=True)
        return href()[url, "[PDF]"]


pybtex.plugin.register_plugin("pybtex.style.formatting", "cda_style", CDAStyle)

bibtex_bibfiles = ["lit_header.bib", "refs.bib"]
bibtex_default_style = "cda_style"

copybutton_prompt_text = r"(?:\(\.?venv\) )?(?:\[.*\] )?\$ "
copybutton_prompt_is_regexp = True
copybutton_line_continuation_character = "\\"

modindex_common_prefix = ["mqt.core."]

autoapi_dirs = ["../python/mqt"]
autoapi_python_use_implicit_namespaces = True
autoapi_root = "api"
autoapi_add_toctree_entry = False
autoapi_ignore = [
    "*/**/_version.py",
]
autoapi_options = [
    "members",
    "show-inheritance",
    "special-members",
    "undoc-members",
]
autoapi_keep_files = True
add_module_names = False
toc_object_entries_show_parents = "hide"
python_use_unqualified_type_names = True
napoleon_google_docstring = True
napoleon_numpy_docstring = False

# AutoAPI renders these annotations as Python cross-references although they
# are typing expressions or private Qiskit aliases, not documented objects.
nitpick_ignore_regex = [
    ("py:class", r"Annotated\[numpy\.typing\.NDArray\[numpy\.complex128\], \{'shape': \(.*\)\}\]"),
    ("py:class", r"Ellipsis"),
    ("py:class", r"ParametersType"),
    ("py:class", r"pennylane\.devices\.DeviceCapabilities"),
    ("py:class", r"pennylane\.tape\.QuantumScriptOrBatch"),
    ("py:class", r"pennylane\.transforms\.core\.CompilePipeline"),
    ("py:class", r"pennylane\.typing\.(Result|ResultBatch)"),
    ("py:class", r"qiskit\.primitives\.containers\.(Estimator|Sampler)PubLike"),
]

# ACM and SIAM reject automated requests after resolving their valid DOI links.
linkcheck_ignore = [r"https://doi\.org/10\.(?:1137|1145)/.*"]

# GitHub renders this valid source-document anchor outside the fetched HTML.
linkcheck_anchors_ignore_for_url = [
    r"https://github\.com/Qiskit/qiskit/blob/cd8701690723d3d9602fac63fe0bd7ea618799be/CONTRIBUTING\.md"
]


cpp_api_tagfile = ("_build/doxygen/mqt-core.tag", "cpp/", "_build/doxygen/xml")
_qdmi_api_base = "https://munich-quantum-software-stack.github.io/QDMI/pr-preview/pr-513/"
qdmi_api_tagfile = (
    "_build/qdmi.tag",
    _qdmi_api_base,
)
qdmi_api_tagfile_url = f"{_qdmi_api_base}qdmi.tag"

# -- Options for HTML output -------------------------------------------------

html_theme = "furo"
html_static_path = ["_static"]
html_js_files = ["cpp-api-navigation.js"]
html_css_files = [
    "custom.css",
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/fontawesome.min.css",
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/solid.min.css",
    "https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/brands.min.css",
]
html_theme_options = {
    "light_logo": "mqt_dark.png",
    "dark_logo": "mqt_light.png",
    "source_repository": "https://github.com/munich-quantum-toolkit/core/",
    "source_branch": "main",
    "source_directory": "docs/",
    "navigation_with_keys": True,
    "footer_icons": [
        {
            "name": "GitHub",
            "url": "https://github.com/munich-quantum-toolkit/core/",
            "html": "",
            "class": "fa-brands fa-solid fa-github fa-2x",
        },
        {
            "name": "PyPI",
            "url": "https://pypi.org/project/mqt-core/",
            "html": "",
            "class": "fa-brands fa-solid fa-python fa-2x",
        },
    ],
}
